version: '3'

vars:
  DB_HOST: localhost
  DB_PORT: 3306
  DB_USER: root
  DB_PASSWORD: root
  DB_NAME: gowoopi

tasks:
  # Infrastructure
  infra:up:
    desc: Start MySQL container
    cmds:
      - docker compose up -d
      - task: infra:wait

  infra:down:
    desc: Stop MySQL container
    cmds:
      - docker compose down

  infra:wait:
    desc: Wait for MySQL to be ready
    cmds:
      - |
        until docker compose exec -T mysql mysqladmin ping -h localhost --silent; do
          echo "Waiting for MySQL..."
          sleep 2
        done
        echo "MySQL is ready!"

  # Backend
  backend:run:
    desc: Run backend server
    dir: backend
    env:
      DB_HOST: "{{.DB_HOST}}"
      DB_PORT: "{{.DB_PORT}}"
      DB_USER: "{{.DB_USER}}"
      DB_PASSWORD: "{{.DB_PASSWORD}}"
      DB_NAME: "{{.DB_NAME}}"
    cmds:
      - go run cmd/server/main.go

  backend:test:
    desc: Run backend tests
    dir: backend
    env:
      TEST_DB_HOST: "{{.DB_HOST}}"
      TEST_DB_PORT: "{{.DB_PORT}}"
      TEST_DB_USER: "{{.DB_USER}}"
      TEST_DB_PASSWORD: "{{.DB_PASSWORD}}"
      TEST_DB_NAME: "{{.DB_NAME}}"
    cmds:
      - go test -v ./...

  backend:lint:
    desc: Run backend linter
    dir: backend
    cmds:
      - golangci-lint run

  # Frontend
  frontend:install:
    desc: Install frontend dependencies
    dir: frontend
    cmds:
      - pnpm install

  frontend:dev:
    desc: Run frontend dev server (all apps)
    dir: frontend
    cmds:
      - pnpm dev

  frontend:customer:
    desc: Run customer app (port 3001)
    dir: frontend/apps/customer-app
    cmds:
      - pnpm dev

  frontend:admin:
    desc: Run admin app (port 3002)
    dir: frontend/apps/admin-app
    cmds:
      - pnpm dev

  frontend:lint:
    desc: Run frontend linter
    dir: frontend
    cmds:
      - pnpm lint

  frontend:test:
    desc: Run frontend tests
    dir: frontend
    cmds:
      - pnpm test

  # Combined
  dev:
    desc: Start all services for local development
    cmds:
      - task: infra:up
      - echo "Run 'task backend:run' and 'task frontend:dev' in separate terminals"

  test:
    desc: Run all tests
    cmds:
      - task: backend:test
      - task: frontend:test

  lint:
    desc: Run all linters
    cmds:
      - task: backend:lint
      - task: frontend:lint

  clean:
    desc: Clean up everything
    cmds:
      - task: infra:down
      - docker volume rm gowoopi_mysql_data 2>/dev/null || true

  # Parallel Development (Git Worktree)
  worktree:setup:
    desc: Setup worktrees for parallel unit development
    cmds:
      - git worktree add ../gowoopi-unit3 -b feat/unit3-customer-app main 2>/dev/null || echo "unit3 worktree already exists"
      - git worktree add ../gowoopi-unit4 -b feat/unit4-admin-app main 2>/dev/null || echo "unit4 worktree already exists"
      - git worktree list
      - |
        echo ""
        echo "✅ Worktrees ready! Open separate terminals:"
        echo "  Terminal 1: cd $(pwd)              # main/backend"
        echo "  Terminal 2: cd $(pwd)/../gowoopi-unit3  # customer-app"
        echo "  Terminal 3: cd $(pwd)/../gowoopi-unit4  # admin-app"

  worktree:list:
    desc: List all worktrees
    cmds:
      - git worktree list

  worktree:clean:
    desc: Remove all worktrees
    cmds:
      - git worktree remove ../gowoopi-unit3 --force 2>/dev/null || true
      - git worktree remove ../gowoopi-unit4 --force 2>/dev/null || true
      - git worktree prune
      - echo "✅ Worktrees removed"
