// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service.go -destination=internal/mock/mock_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	model "github.com/kohwg/gowoopi/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// AdminLogin mocks base method.
func (m *MockAuthService) AdminLogin(req model.AdminLoginRequest) (*model.AuthResponse, *model.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminLogin", req)
	ret0, _ := ret[0].(*model.AuthResponse)
	ret1, _ := ret[1].(*model.TokenPair)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AdminLogin indicates an expected call of AdminLogin.
func (mr *MockAuthServiceMockRecorder) AdminLogin(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminLogin", reflect.TypeOf((*MockAuthService)(nil).AdminLogin), req)
}

// CustomerLogin mocks base method.
func (m *MockAuthService) CustomerLogin(req model.CustomerLoginRequest) (*model.AuthResponse, *model.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomerLogin", req)
	ret0, _ := ret[0].(*model.AuthResponse)
	ret1, _ := ret[1].(*model.TokenPair)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CustomerLogin indicates an expected call of CustomerLogin.
func (mr *MockAuthServiceMockRecorder) CustomerLogin(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomerLogin", reflect.TypeOf((*MockAuthService)(nil).CustomerLogin), req)
}

// GenerateTokenPair mocks base method.
func (m *MockAuthService) GenerateTokenPair(claims model.Claims) (*model.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPair", claims)
	ret0, _ := ret[0].(*model.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenPair indicates an expected call of GenerateTokenPair.
func (mr *MockAuthServiceMockRecorder) GenerateTokenPair(claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPair", reflect.TypeOf((*MockAuthService)(nil).GenerateTokenPair), claims)
}

// RefreshToken mocks base method.
func (m *MockAuthService) RefreshToken(refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServiceMockRecorder) RefreshToken(refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthService)(nil).RefreshToken), refreshToken)
}

// ValidateToken mocks base method.
func (m *MockAuthService) ValidateToken(token string) (*model.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", token)
	ret0, _ := ret[0].(*model.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAuthServiceMockRecorder) ValidateToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAuthService)(nil).ValidateToken), token)
}

// MockMenuService is a mock of MenuService interface.
type MockMenuService struct {
	ctrl     *gomock.Controller
	recorder *MockMenuServiceMockRecorder
	isgomock struct{}
}

// MockMenuServiceMockRecorder is the mock recorder for MockMenuService.
type MockMenuServiceMockRecorder struct {
	mock *MockMenuService
}

// NewMockMenuService creates a new mock instance.
func NewMockMenuService(ctrl *gomock.Controller) *MockMenuService {
	mock := &MockMenuService{ctrl: ctrl}
	mock.recorder = &MockMenuServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuService) EXPECT() *MockMenuServiceMockRecorder {
	return m.recorder
}

// CreateMenu mocks base method.
func (m *MockMenuService) CreateMenu(storeID string, req model.MenuCreateRequest) (*model.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMenu", storeID, req)
	ret0, _ := ret[0].(*model.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMenu indicates an expected call of CreateMenu.
func (mr *MockMenuServiceMockRecorder) CreateMenu(storeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMenu", reflect.TypeOf((*MockMenuService)(nil).CreateMenu), storeID, req)
}

// DeleteMenu mocks base method.
func (m *MockMenuService) DeleteMenu(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMenu", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMenu indicates an expected call of DeleteMenu.
func (mr *MockMenuServiceMockRecorder) DeleteMenu(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMenu", reflect.TypeOf((*MockMenuService)(nil).DeleteMenu), id)
}

// GetMenusByStore mocks base method.
func (m *MockMenuService) GetMenusByStore(storeID string) ([]model.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenusByStore", storeID)
	ret0, _ := ret[0].([]model.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenusByStore indicates an expected call of GetMenusByStore.
func (mr *MockMenuServiceMockRecorder) GetMenusByStore(storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenusByStore", reflect.TypeOf((*MockMenuService)(nil).GetMenusByStore), storeID)
}

// UpdateMenu mocks base method.
func (m *MockMenuService) UpdateMenu(id uint, req model.MenuUpdateRequest) (*model.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMenu", id, req)
	ret0, _ := ret[0].(*model.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMenu indicates an expected call of UpdateMenu.
func (mr *MockMenuServiceMockRecorder) UpdateMenu(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMenu", reflect.TypeOf((*MockMenuService)(nil).UpdateMenu), id, req)
}

// UpdateMenuOrder mocks base method.
func (m *MockMenuService) UpdateMenuOrder(items []model.MenuOrderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMenuOrder", items)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMenuOrder indicates an expected call of UpdateMenuOrder.
func (mr *MockMenuServiceMockRecorder) UpdateMenuOrder(items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMenuOrder", reflect.TypeOf((*MockMenuService)(nil).UpdateMenuOrder), items)
}

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
	isgomock struct{}
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderService) CreateOrder(storeID, sessionID string, tableID uint, req model.OrderCreateRequest) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", storeID, sessionID, tableID, req)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderServiceMockRecorder) CreateOrder(storeID, sessionID, tableID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderService)(nil).CreateOrder), storeID, sessionID, tableID, req)
}

// DeleteOrder mocks base method.
func (m *MockOrderService) DeleteOrder(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockOrderServiceMockRecorder) DeleteOrder(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockOrderService)(nil).DeleteOrder), id)
}

// GetOrdersBySession mocks base method.
func (m *MockOrderService) GetOrdersBySession(sessionID string) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersBySession", sessionID)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersBySession indicates an expected call of GetOrdersBySession.
func (mr *MockOrderServiceMockRecorder) GetOrdersBySession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersBySession", reflect.TypeOf((*MockOrderService)(nil).GetOrdersBySession), sessionID)
}

// GetOrdersByStore mocks base method.
func (m *MockOrderService) GetOrdersByStore(storeID string) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByStore", storeID)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByStore indicates an expected call of GetOrdersByStore.
func (mr *MockOrderServiceMockRecorder) GetOrdersByStore(storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByStore", reflect.TypeOf((*MockOrderService)(nil).GetOrdersByStore), storeID)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderService) UpdateOrderStatus(id string, req model.StatusUpdateRequest) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", id, req)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderServiceMockRecorder) UpdateOrderStatus(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderService)(nil).UpdateOrderStatus), id, req)
}

// MockTableService is a mock of TableService interface.
type MockTableService struct {
	ctrl     *gomock.Controller
	recorder *MockTableServiceMockRecorder
	isgomock struct{}
}

// MockTableServiceMockRecorder is the mock recorder for MockTableService.
type MockTableServiceMockRecorder struct {
	mock *MockTableService
}

// NewMockTableService creates a new mock instance.
func NewMockTableService(ctrl *gomock.Controller) *MockTableService {
	mock := &MockTableService{ctrl: ctrl}
	mock.recorder = &MockTableServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableService) EXPECT() *MockTableServiceMockRecorder {
	return m.recorder
}

// CompleteTable mocks base method.
func (m *MockTableService) CompleteTable(tableID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTable", tableID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteTable indicates an expected call of CompleteTable.
func (mr *MockTableServiceMockRecorder) CompleteTable(tableID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTable", reflect.TypeOf((*MockTableService)(nil).CompleteTable), tableID)
}

// GetTableHistory mocks base method.
func (m *MockTableService) GetTableHistory(tableID uint, from, to *time.Time) ([]model.OrderHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableHistory", tableID, from, to)
	ret0, _ := ret[0].([]model.OrderHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableHistory indicates an expected call of GetTableHistory.
func (mr *MockTableServiceMockRecorder) GetTableHistory(tableID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableHistory", reflect.TypeOf((*MockTableService)(nil).GetTableHistory), tableID, from, to)
}

// SetupTable mocks base method.
func (m *MockTableService) SetupTable(storeID string, req model.TableSetupRequest) (*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupTable", storeID, req)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupTable indicates an expected call of SetupTable.
func (mr *MockTableServiceMockRecorder) SetupTable(storeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupTable", reflect.TypeOf((*MockTableService)(nil).SetupTable), storeID, req)
}

// MockSSEManager is a mock of SSEManager interface.
type MockSSEManager struct {
	ctrl     *gomock.Controller
	recorder *MockSSEManagerMockRecorder
	isgomock struct{}
}

// MockSSEManagerMockRecorder is the mock recorder for MockSSEManager.
type MockSSEManagerMockRecorder struct {
	mock *MockSSEManager
}

// NewMockSSEManager creates a new mock instance.
func NewMockSSEManager(ctrl *gomock.Controller) *MockSSEManager {
	mock := &MockSSEManager{ctrl: ctrl}
	mock.recorder = &MockSSEManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSEManager) EXPECT() *MockSSEManagerMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockSSEManager) Broadcast(storeID string, event model.SSEEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", storeID, event)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockSSEManagerMockRecorder) Broadcast(storeID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockSSEManager)(nil).Broadcast), storeID, event)
}

// Subscribe mocks base method.
func (m *MockSSEManager) Subscribe(storeID string) chan model.SSEEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", storeID)
	ret0, _ := ret[0].(chan model.SSEEvent)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSSEManagerMockRecorder) Subscribe(storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSSEManager)(nil).Subscribe), storeID)
}

// Unsubscribe mocks base method.
func (m *MockSSEManager) Unsubscribe(storeID string, ch chan model.SSEEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", storeID, ch)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockSSEManagerMockRecorder) Unsubscribe(storeID, ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockSSEManager)(nil).Unsubscribe), storeID, ch)
}
